apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: anobahe/udagram-api-feed:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "8240Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secret