apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-user
spec:
  selector:
    matchLabels:
      run: backend-api-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-api-user
    spec:
      containers:
      - name: backend-api-user
        image: anobahe/udagram-api-user
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m