apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-backend-feed
spec:
  selector:
    matchLabels:
      run: udagram-backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: udagram-backend-feed
    spec:
      containers:
      - name: udagram-backend-feed
        image: anobahe/udagram-api-feed
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m